pipeline {
    agent any

    tools {
    'org.jenkinsci.plugins.docker.commons.tools.DockerTool' '18.09'
  }

    stages {

        stage('Run Scan') {

           options {
                timeout(time: 10, unit: 'MINUTES')
            }

            steps {
                git 'https://github.com/danielitogomez/automation-scanning'
                sh 'docker version'
                //sh 'chmod +x run.sh && ./run.sh'
            }
            
           post {
                always {
                    sh 'echo "todo bien?"'
                }
            }
            
            
        }
        
    }
}