name: target Scan

on:
  push:
    branches:
      - master
    paths:
      - targets.txt
  pull_request:
    branches:
      - master
    paths:
      - targets.txt
  workflow_dispatch: # Allows manual triggering

jobs:
  target-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Testing ping
        run: ping www.google.com
        
#      - name: Checkout repository
#        uses: actions/checkout@v2

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

#      - name: Build Docker image
#        run: docker build -t target-scan .

#      - name: Run target scan
#        run: docker run target-scan
